### ISSUE TITLE
custom outdated client text

### ISSUE THREAD

**Issue by TheosisOfficial** [strumswell/ServerlistMOTD-X#11]
Hi, I'm sorry if this is not a bug (if not, I guess it would count as a feature request), but I couldn't find a more relevant place to put this.

When the version text module is enabled, no matter which version of Minecraft I use (even if it's the correct version for the server), the text shows up. However, I only want this text to appear when someone is using the _wrong_ version (basically, instead of the server saying "Spigot 1.x.x", I want to change it to something else, such as "You must use Minecraft 1.x.x" in order to make it more intuitive and make more sense to regular players). I'm assuming the fact that this doesn't already happen is a bug, but if that is not the case, then consider this a feature request (being able to customise the version text _only_ when someone is using an outdated or too updated client).

Great plugin. Any help would be appreciated! :)

**Comment by strumswell** [comment]
Hey there!
Yeah, you're right. This is not a bug. I'm just going to gently push you to the [FAQ](https://github.com/strumswell/ServerlistMOTD-X/issues/5) or this issue https://github.com/strumswell/ServerlistMOTD-X/issues/5 for an explanation. :)

Sounds like a good idea to implement. As you might know, I'm not actively supporting this project anymore. I only do bug fixes to keep the project alive. But I am going to leave this request open in case I want to implement new things in the future. You never know. :)

Thank you for the nice words!

**Comment by TheosisOfficial** [comment]
Ah sorry, I somehow managed to miss the big red text saying that you're not supporting the project anymore. :)

I'm almost certain I've achieved what I mentioned here in the past with a plugin called ServerListPlus (which is not maintained anymore, which is why I decided to use your plugin instead), but I could be wrong.

If you can't/don't want to implement it, it's really not a big deal at all. Thanks for the response! :)

**Comment by strumswell** [comment]
ServerListPlus is an excellent plugin written by a nice guy. It's a great alternative if you're looking for something outside of vanilla Spigot. Great tip, gonna look into it eventually.

**Comment by strumswell** [comment]
```
 OutdatedClientText:
    Enable: true
    Message: 'Use Minecraft 1.16 &r&7%realonline%&8/&7%realslots%'
```

Supporting variable: %realslots%, %realonline%", %fakeonline%", %fakeslots%", %slotsplusone%", %randomnumber%", PlaceholderAPI (non Player!)

<img width="613" alt="Bildschirmfoto 2020-09-02 um 12 18 34" src="https://user-images.githubusercontent.com/6720421/91969737-deb9bf80-ed16-11ea-8c30-87263461987c.png">

**Comment by TheosisOfficial** [comment]
> ```
>  OutdatedClientText:
>     Enable: true
>     Message: 'Use Minecraft 1.16 &r&7%realonline%&8/&7%realslots%'
> ```
> 
> Supporting variables: %realslots%, %realonline%, %fakeonline%, %fakeslots%, %slotsplusone%, %randomnumber%, PlaceholderAPI (non Player!)
> 
> <img alt="Bildschirmfoto 2020-09-02 um 12 18 34" width="613" src="https://user-images.githubusercontent.com/6720421/91969737-deb9bf80-ed16-11ea-8c30-87263461987c.png">
> 
> (When pinging a Paper 1.16 server with 1.12 client)

Amazing!! When will the release be posted on Bukkit?

**Comment by strumswell** [comment]
Not sure tbh. I still have to do some testing and minor internal tweaks. But I can attach a current dev build here for you if you want to use the feature(s) now. Just keep in mind that some things may be buggy as some internal stuff has changed. But everything seemed fine in my limited testing period so far. So let me know...

**Comment by TheosisOfficial** [comment]
> Not sure tbh. I still have to do some testing and minor internal tweaks. But I can attach a current dev build here for you if you want to use the feature(s) now. Just keep in mind that some things may be buggy as some internal stuff has changed. But everything seemed fine in my limited testing period so far. So let me know...

That's okay, I can wait for the Bukkit release. :)

**Comment by strumswell** [comment]
Update is online here on [GitHub](https://github.com/strumswell/ServerlistMOTD-X/releases/tag/X-2020-09-05) under review on [dev.bukkit.org](https://dev.bukkit.org/projects/serverlistmotd/files). It's going to be available in a few hours.

**Comment by strumswell** [comment]
Part of newest release:
https://dev.bukkit.org/projects/serverlistmotd/files/3050444
https://github.com/strumswell/ServerlistMOTD-X/releases/tag/X-2020-09-05
