### ISSUE TITLE
%displayname%

### ISSUE THREAD

**Issue by strumswell** [strumswell/ServerlistMOTD-X#14]
> It would be great to add more variables, for example displayname - this would be useful on RP servers, where the player's displayed nickname is usually changed to RP-name.

See [dev.bukkit#216](https://dev.bukkit.org/projects/serverlistmotd?comment=216)

**Comment by strumswell** [comment]
Display name is accessible via a Player object https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getDisplayName() which is not available for OfflinePlayer in the serverlist.
 
Possible solution: store it somewhere onJoin/ onLeave and write it to disk on server shutdown. But I‘m not so sure if it’s worth it tbh...

**Comment by Darutan92** [comment]
Okay, thanks for explaining how this works. It is a pity that when logging out of a player's server, this cannot be used.
