### ISSUE TITLE
1.17 Situation

### ISSUE THREAD

**Issue by TheCrafter8000** [strumswell/ServerlistMOTD-X#28]
Serverlist does not work with 1.17

**Comment by strumswell** [comment]
I haven't tested ServerlistMOTD with the latest version yet. Can you elaborate on what errors you get? I guess it's due to ProtocolLib which hasn't gotten an update yet. I'll defiantly come up with a solution like I did with 1.16 when ProtocolLib wasn't ready yet.

**Comment by strumswell** [comment]
Ok, small update from my side.

#### What happened?
Mojang released the 1.17 update and the amazing Spigot team shared their 1.17 update with us this Friday. Many plugins, including ProtocolLib which ServerlistMOTD depends on for slots related features, hasn't gotten an update yet.

#### What now?
Basically what we did when 1.16 came out. I released a lite version of ServerlistMOTD **without** you needing to use ProtocolLib. This also means that I had to disable all slots related features. Lite compares to the last full version of ServerlistMOTD as follows:

Download LITE-X-2021-06-13: [click](https://github.com/strumswell/ServerlistMOTD-X/releases/tag/LITE-X-2021-06-13)


| Feature            | LITE-X-2021-06-13 | X-2020-09-05 |
|--------------------|-------------------|--------------|
| Works with        |   1.17 and below               | 1.16 and below             |
| ClassicMotd        |   🟢                | 🟢             |
| RandomMotd         |  🟢                 |   🟢           |
| BanMotd            |  🟢                 |   🟢           |
| WhitelistMotd      |   🟢                | 🟢             |
| RestrictedMode     |  🟠                 |   🟢           |
| FakeMaxPlayer      |   🔴                |   🟢           |
| FakeOnlinePlayer   |  🔴                 | 🟢             |
| VersionText        |  🔴                 |   🟢           |
| OutdatedClientText | 🔴                  | 🟢             |
| UnknownSlots       |  🔴                 |   🟢           |
| SlotsPlusOne       |   🔴                |   🟢           |
| OnlineMultiplier   |   🔴                |   🟢           |
| HoverText          |  🔴                 |   🟢           |

[The developer of ProtocolLib recommends using ViaVersion with Spigot 1.16 to allow 1.17 player to join.](https://github.com/dmulloy2/ProtocolLib/issues/1209) In this case, you can use the latest version ProtocolLib and X-2020-09-05 with all features just fine. If you want a 1.17 server, this lite version is for you.

When ProtocolLib gets an update, you can switch back to X-2020-09-05 and get all features back. In the meantime, you can check https://github.com/dmulloy2/ProtocolLib/issues/1209 for updates.

**Comment by strumswell** [comment]
Quick update: ProtocolLib for 1.17 is available. You can use the 'ol X-2020-09-05 with the newest dev builds of ProtocolLib. Check this [table with compatibility and downloads](https://github.com/strumswell/ServerlistMOTD-X#versions).
