### ISSUE TITLE
Messages not working correctly

### ISSUE THREAD

**Issue by TheCrafter8000** [strumswell/ServerlistMOTD-X#29]
Hi recently for the past few months the plugin is not saving my ip correctly. It keeps showing me the newbie message or just showing me welcome back messages from other users. I was using serverlistplus at the time and even sense I switched server providers it has been doing this. I tried completely deleting the plugin and it didnt work. Now I switch to this plugin serverlistmotd x and it still does the same thing. How do I fix this?

**Comment by strumswell** [comment]
Hey! Can you answer me the following things:

1. Are you using a VPN?
2. Are you the only one playing on your server from you home internet connection?
3. Do you have a fixed or dynamic/ changing home IP address?
4. Which version of Spigot, ServerlistMOTD and ProtocolLib are you using? Which other plugins are you using?
5.  Have you tried deleting the IP_UUID.dat? (warning: this will reset all known player data)

Let's see if we can solve this problem.

**Comment by TheCrafter8000** [comment]
1. No I am not using a VPN
2. Yes I am using my home internet connection
3. idk (I believe I have a static)
4. Im using PaperMC 1.17 (not sure what verison)
5. Yes and it just regenerates with the same exact data

**Comment by TheCrafter8000** [comment]
Everyone else that plays the server has the same issue as me

**Comment by strumswell** [comment]
4. Can you also tell me which version of ServerlistMOTD and ProtocolLib you are using. And your other plugins? Did you have this problem pre-1.17?
5. You have to delete it while the server is stopped. Can you please re-try?

If the problem persists after doing 5. let me know.

Also, would you mind sharing the IP_UUID.dat with me? If you have no problem with that, you can send it to me via philipp@bolte.cloud

**Comment by TheCrafter8000** [comment]
4. I'm using version v4.7.0-SNAPSHOT-b512 of ProtocolLib. I'm using version vX-2020-09-05 of ServerlistMOTD X. I never had this issue on my old server host but when I transferred the files to the new server host this issue started. I transferred hosts around late Feburary.
5. I just tried that and the IP's are reset but the custom messages are still not working

**Comment by strumswell** [comment]
Can you take a look into the IP_UUID.dat with an editor of your choice? Are the IPs different? Is there more than one entry.

**Comment by TheCrafter8000** [comment]
Here is my IP_UUID.dat

https://www.filemail.com/d/iutcvsceqtdhmwq

**Comment by strumswell** [comment]
Thanks for attaching the IP_UUID.dat! Weirdly, the IPs of all players belong to the OVH IP range. So I guess your hosting provider proxies all user connections and gives them a new IP. That would also explain why known players get the wrong user name or are identified as a newbie – your hosting provider, or whomever, assigns your players a new IP or a previously used IP by another player.

Are you using some kind of domain for connecting to your server? In that case, maybe your proxy (nginx, apache) is misconfigured.

**Comment by TheCrafter8000** [comment]
I'm using pebblehost and I'm using the TCP Shield to create the domain

**Comment by strumswell** [comment]
There you go, TCP Shield seems to be the culprit. I think you have two options:

1. You absolutely need TCP Shield. If that's the case there is nothing I can do to make the player recognition work, as TCP Shield proxies all connections through their infrastructure iiuc. Don't use %player% and configure the same motd for newbie and regulars to to have a deterministic motd.
2. You don't need TCP shield. So turn it off and everything should start working again on the ServerlistMOTD side. If you just need a domain, you only have to configure the A and SRV entry in your DNS settings @ domain registrar afaik. 

Let me know if you can close the issue now.

**Comment by TheCrafter8000** [comment]
Ok it could seem like that but for some reason the firewall looks like this. The IP_UUID.dat is similar or the same to the firewall configurations.
https://ibb.co/2ZHYcFf
https://ibb.co/gwjGny5
https://www.filemail.com/d/jllgnljeasgjysc

**Comment by strumswell** [comment]
The firewall rules are what one should expect from a service like that. I can't give you support for TCP Shield though. But you won't solve your problem by looking at firewall rules. You somehow have to preserve the origin IP of the request and stop the mapping of IP addresses to internal ones you see in the firewall rules. Just hit up TCP Shield and ask what you can do so that their product doesn't fuck up IP-based plugins like mine.

I close this issue now as this is nothing related to ServerlistMOTD. But please keep me updated here as I would like to know if you could eventually solve your problem.

**Comment by TheCrafter8000** [comment]
Ok Thank You for the help
