### ISSUE TITLE
1.14.4?

### ISSUE THREAD

**Issue by Peter-Crawley** [strumswell/ServerlistMOTD-X#3]
Is it possible to add support for 1.14.4?

**Comment by strumswell** [comment]
Hi Peter. I tested the last version with 1.14.1. How does the incompatibility show? Can you send me a full server log with the error messages. I can get behind it. :-)

**Comment by strumswell** [comment]
Short update: I tested the newest version of ServerlistMOTD with Spigot 1.14.4 and ProtocolLib 4.3.0. Everything works fine. Can you define what's not working?

**Comment by Peter-Crawley** [comment]
I did not notice it needed a library. Sorry for wasting your time.

**Comment by strumswell** [comment]
No problem. 😁
