### ISSUE TITLE
Paper complains about logging

### ISSUE THREAD

**Issue by atlgeek007** [strumswell/ServerlistMOTD-X#31]
In the newest paper 1.17.1 builds, I see this message whenever the IP_UUID.dat file gets saved:

```
[Tue, 3. Aug 2021 19:13:51 CDT INFO] [STDOUT] [ServerlistMOTD] Saved userdata into IP_UUID.dat in 1ms.
[Tue, 3. Aug 2021 19:13:51 CDT WARN] Nag author(s): '[Strumswell]' of 'ServerlistMOTD' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
```
Not a huge deal but I figured I'd bring it to your attention.

**Comment by SpiffyJUNIOR** [comment]
Same exact issue here, using paper 1.17.1.

**Comment by strumswell** [comment]
If you'd like to, you can check out the beta. I've included your feedback.

https://github.com/strumswell/ServerlistMOTD-X/releases/tag/X-2021-09-12-BETA
