### ISSUE TITLE
Issue with latest beta build

### ISSUE THREAD

**Issue by ConaII** [strumswell/ServerlistMOTD-X#36]
Trying to use the ClassicMotd will add [Line, Line] to the motd:
![image](https://user-images.githubusercontent.com/72966048/140881403-b8c05527-acf9-42c4-b912-5970fcce3856.png)

Also using empty slots in RestrictedMode gives []

**Comment by strumswell** [comment]
Can you share your config.yml?

**Comment by ConaII** [comment]
# ----------------------------------------- [ Configuration File ]  ------------------------------------------ #
# FAQ:
#   - "Why IP Logging?": Needed for identifying players in the serverlist by their IP. Used in %player%, %money"
#      IPs and UUIDs of players are stored locally inside the IP_UUID.dat.
#   - "Connection turns red in serverlist with VersionText on.": Ever seen when your server is outdated in the
#      serverlist? SMOTD simulates this and changes the text. This is just cosmetical!
#   - "Plugin ServerlistMOTD created a profile with 'HoverText' as an UUID.": Your HoverText normally
#      contains a list of players. SMOTD clears that and creates a fake player with your text as its name.
#   - "What is Regulars and Newbies?" Players are categorized in those two groups in the list. Regular players
#      are known by their ip while newbies are not.
#   - "Player related placeholders from PlaceholderAPI are not working!": This is a known limitation. All this
#      information is not available in the serverlist because the player isn't online.
# ----------------------------------------- [ Configuration File ]  ------------------------------------------ #

ClassicMotd:
  Regulars:
    - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------&r'
    - '<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)&r'
    #- '&2Welcome back, &e%player%&2! %line%&aIt''s a %weather% %time%.'
  Newbies: 
    - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------&r'
    - '<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)&r'
    #- '&2Welcome newbie! %line%&aIt''s a %weather% %time%.'
RandomMotd:
  Enable: true
  Regulars: 
    - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------&r%line%<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)&r'
  Newbies: 
    - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------&r%line%<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)&r'
RestrictedMode: 
BanMotd:
  Enable: false
  MessageTempBan:
    - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------
    %line%<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)
    %line%&cYou are banned! Reason: &e%reason%%line%&cExpiration: &e%expdate% at %exptime%'
  MessageForeverBan: 
    - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------
    %line%<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)
    %line%&cYou are banned! Reason: &e%reason%%line%&cExpiration: &eNEVER'
  Format:
    Date: 'DD/MM/YYYY'
    Time: 'hh:mm:ss'
WhitelistMotd:
  Enable: false
  MessageWhitelisted:
    - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------
    %line%<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)
    %line%&e%player% &c&oYou are on the whitelist.'
  MessageNotWhitelisted: 
    - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------'
    - '%line%<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)'
    - '%line%&cYou are &lNOT &cwhitelisted.&c&oPlease contact the server owner.'
RestrictedMode:
  Enable: false
  Motd:
    AccessGranted:
        - '&6&o-----------<#373330>(<#c48b59>&lHistorika<#373330>)&6&o-----------
        %line%<#7d86a0>Server Geopolitico RP Towny <#e9ae43>(1.16 - 1.17)
        %line%&e%player% &4Servidor restringido, tienes permisos para entrar.'
    AccessDenied: '&4Can''t connect to server.'
    KickMessage: 'java.net.ConnectException: Connection timed out: no further information:'
  Slots:
    VersionText: 
        - ''
Slots:
  FakeMaxPlayer:
    Enable: false
    Number: 200
  FakeOnlinePlayer:
    Enable: false
    Number: 122
    RandomNumber:
      Enable: false
      Max: 100
      Min: 90
  VersionText:
    Enable: true
    Message: '&6Entra ya!  &7%realonline%&8/&7%realslots%'
  OutdatedClientText:
    Enable: true
    Message: '&cUse Minecraft 1.16 &r&7%realonline%&8/&7%realslots%'
  UnknownSlots:
    Enable: false
  SlotsPlusOne:
    Enable: false
    MinSlots: 5
    MaxSlots: 100
    AddSlotsToOnline: 1
  OnlineMultiplier:
    Enable: false
    MinSlots: 100
    MaxSlots: 2500
    AddSlotsWhenOnline>MinSlots: 1
    MultiplyBy: 5
  HoverText:
    Enable: true
    Messages:
      - '&cServidor de RP-Geopolitico BETA'
      - ' &e-> Is this for you?'
      - ' &e-> Entra ya, sera diveritido.'
      - '&6'
Variables:
  TimeVariable:
    NightText: night
    DayText: day
    World: world
  WeatherVariable:
    RainText: rainy
    SunText: clear
    World: world
  RandomNumberVariable:
    Max: 100
    Min: 90
  RandomPlayerVariable:
    UseTextWhenNobodyOnline:
      Enable: false
      Text: 'Player'
    UseDatabaseNameWhenNobodyOnline:
      Enable: true
AutoSaveConfig:
  IntervalInMin: 30
DoNOTtouchMe: 10.1

**Comment by ConaII** [comment]
https://pastebin.com/Dd6QGZxR

**Comment by ConaII** [comment]
I've disabled the ClassicMotd, this does not happen in random motds.

**Comment by strumswell** [comment]
Your config is absolutely fucked in many places. Let me fix this up and see if I can reproduce the described problems.

**Comment by strumswell** [comment]
Ok, good news. You only messed up your config. Here is a fixed version: https://pastebin.com/CEsf6Rp9

Things you have to look out for:
- Bullet points, like `-`, are only allowed in RandomMOTD and HoverText. In all other places, only a single string is allowed.
- You can use `%line%` only one time. A server motd can only have TWO lines total. You were trying three sometimes.
- Don't add line breaks, e.g. via enter, in front of a `%line%`. YAML doesn't like that.

When in doubt, have a look at the default [config](https://github.com/strumswell/ServerlistMOTD-X/blob/master/config.yml) or the [wiki](https://github.com/strumswell/ServerlistMOTD-X/wiki) describing the most important things.

Let me know if this fixed your problems.

<img width="768" alt="Bildschirmfoto 2021-11-11 um 14 11 20" src="https://user-images.githubusercontent.com/6720421/141305655-77d6d387-78dd-4ab9-9a17-17d69f00c152.png">
<img width="773" alt="Bildschirmfoto 2021-11-11 um 14 13 02" src="https://user-images.githubusercontent.com/6720421/141305657-cc3bcbd4-3712-4be8-99bc-f56e268b4cbe.png">

**Comment by strumswell** [comment]
Yeah, don't really care about that. Are your problems fixed?

**Comment by ConaII** [comment]
Yes
