### ISSUE TITLE
UnknownSlots doesn't work

### ISSUE THREAD

**Issue by magne37** [strumswell/ServerlistMOTD-X#44]
When turning on UnknownSlots in the config.yml file, nothing happens. I am on version 1.18.2, however, this also doesn't work on 1.18.1.

**To Reproduce:**
Set UnknownSlots to true in config.yml
Expected behavior: The player slots should be replaced by "???".

Config.yml: https://pastebin.com/zciHbbdM

**Versions:**
Spigot: latest
ServerlistMOTD: Nov 23rd, 2021
ProtocolLib: Build 549

**Comment by strumswell** [comment]
It seems you have already found a solution. Couldn't recreate your problem btw. Let me know what the problem was.

**Comment by magne37** [comment]
> It seems you have already found a solution. Couldn't recreate your problem btw. Let me know what the problem was.

Yeah I got it to work, seems the ProtocolLib link you linked on your bukkit page wasn’t updated, so I had to download a newer version of ProtocolLib from their site.
