### ISSUE TITLE
Might already be here, but is it possible to make version text different color

### ISSUE THREAD

**Issue by Zyriom** [strumswell/ServerlistMOTD-X#45]
hi, i want to make text on VersionText (next to ping bar) different colors and not red. is this possible?

**Comment by strumswell** [comment]
Sure? The default config already applies custom colors to the text, right? I don't get your question.

**Comment by strumswell** [comment]
```
VersionText:
    Enable: false
    Message: '&aJoin now!  &e%realonline%/%realslots%'
```

**Comment by strumswell** [comment]
Maybe you mean the crossed out ping bars? Expected behavior, see #38 #5 the wiki and your config header
