### ISSUE TITLE
BanMotd not working with AdvancedBan

### ISSUE THREAD

**Issue by trc99** [strumswell/ServerlistMOTD-X#47]
Ban motd not working

i set true in config, rebooted the server, banned myself and banmotd is not showing

https://pastebin.com/gYZ9sidv

**Versions (please complete the following information):**
 - paper 1.18.2-278
 - last dev build serverlist motd x
 - ProtocolLib 
 - advancedban 2.3

help plz

**Comment by strumswell** [comment]
Heyo,

AdvancedBan is not supported with BanMotd. You can find a list of supported ban plugins here: https://github.com/strumswell/ServerlistMOTD-X/wiki/4.-BanMOTD

If you would like to see AdvancedBan support, please create a new feature request ticket. :)

**Comment by trc99** [comment]
thx!
