### ISSUE TITLE
What to do when there is no config.yml?

### ISSUE THREAD

**Issue by ghost** [strumswell/ServerlistMOTD-X#49]
**Describe the bug**
My server uses server.properties as the property file for the server itself, and bukkit.yml + spigot.yml for that configuration. My server uses Spigot, running on Debian 11 with 1.18.2 server.
So whenever I start the server, it uses the motd in server.properties which uses a completely different format to what is in the typical config.yml
![Screenshot_20220601-131121-822](https://user-images.githubusercontent.com/100100163/171485214-a89375b3-3bac-42e5-812b-0fb4a0c6d895.png)

**Expected behavior**
Expected to find config.yml file.

**Config**
https://pastebin.com/gs9t4Efh

**Versions (please complete the following information):**
 - Spigot - Latest (1.18.2)
 - ServerlistMOTD - Latest
 - ProtocolLib - Not Installed

**Comment by strumswell** [comment]
Hm, I really have a hard time understanding your problem. So have you:
1. Added the ServerlistMOTD.jar to your /plugins folder
2. Started the server once
3. Checked that the config.yml appears in /plugins/ServerlistMOTD?

Can you maybe attach a log of your server starting?

**Comment by ghost** [comment]
1. Yes it is in the plugins folder
2. It has started without any error messages
3. There is no config.yml file in the plugins folder that ServerlistMOTD.jar is located in

**Comment by strumswell** [comment]
Can you please share a log of your spigot server starting up?

**Comment by ghost** [comment]
`latest.log`: https://pastebin.com/5ynfaUGi

**Comment by strumswell** [comment]
Could you delete the ServerlistMOTD.jar, redownload it and start the server again? The plugin is not even loading for you, which is super weird.

What version of Java are you running?

**Comment by ghost** [comment]
I managed to fix the problem. Reinstalling the ServerlistMOTD.jar seemed to
fix it. I'm running 1.18.2
