### ISSUE TITLE
Error everytime a new player views the MOTD

### ISSUE THREAD

**Issue by cheexe** [strumswell/ServerlistMOTD-X#7]
https://pastebin.com/bTeX1dT1

14.05 08:38:34 [Server] ERROR Could not pass event StandardPaperServerListPingEventImpl to ServerlistMOTD vX-2020-03-02
14.05 08:38:34 [Server] INFO java.lang.IllegalArgumentException: UUID cannot be null
14.05 08:38:34 [Server] INFO at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.getOfflinePlayer(CraftServer.java:1502) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:890) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at cloud.bolte.serverlistmotd.motd.MaxBansMotd.setBanMotd(MaxBansMotd.java:82) ~[?:?]
14.05 08:38:34 [Server] INFO at cloud.bolte.serverlistmotd.events.Ping.onPing(Ping.java:54) ~[?:?]
14.05 08:38:34 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor479.execute(Unknown Source) ~[?:?]
14.05 08:38:34 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:80) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at net.minecraft.server.v1_15_R1.PacketStatusListener.a(PacketStatusListener.java:138) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at net.minecraft.server.v1_15_R1.PacketStatusInStart.a(SourceFile:22) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at net.minecraft.server.v1_15_R1.PacketStatusInStart.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:158) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at net.minecraft.server.v1_15_R1.NetworkManager.channelRead0(NetworkManager.java:147) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at net.minecraft.server.v1_15_R1.NetworkManager.channelRead0(NetworkManager.java:29) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) ~[?:?]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at net.minecraft.server.v1_15_R1.LegacyPingHandler.channelRead(LegacyPingHandler.java:120) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.15.2.jar:git-Paper-282]
14.05 08:38:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by strumswell** [comment]
Hey there. Can you give me the following infos:
- version of ServerlistMOTD
- version of ProtocolLib
- your config.yml (https://pastebin.com)
- your usercache.json (https://pastebin.com)
- your version of paper (note: paper spigot isn't officially supported but I'm going to look into it)
- When the user joins, then quits and rechecks the motd, do you get the error as well?

**Comment by cheexe** [comment]
My config.yml https://pastebin.com/iBqvPs0R
My usercache.json https://pastebin.com/LyYUUEZc 
MaxBans v2.7

**Comment by strumswell** [comment]
So you have the BanMotd disabled while getting the error, correct? I am currently a little bit under time pressure so I might not be able to fix your problem instantly. So please have some patience with me :)

**Comment by strumswell** [comment]
So this might have been an easy fix. Found a few problematic things. Can you test this version? I don't have to time for checking but it should be fine. Please report back so I can release the fix.

[ServerlistMOTD_2020-05-14.jar.zip](https://github.com/strumswell/ServerlistMOTD-X/files/4628827/ServerlistMOTD_2020-05-14.jar.zip)

**Comment by cheexe** [comment]
Yes, i get this error when BanMotd is disabled, i will try the file you sent.

**Comment by cheexe** [comment]
So far i dont get the error with the version you sent me.

**Comment by strumswell** [comment]
Great, keep me updated with your experience. Gonna wait a week and do some testing myself before releasing. Thank you very much for reporting this bug. :)

**Comment by cheexe** [comment]
Ill keep you updated, thanks for the fast help :))

**Comment by strumswell** [comment]
Part of newest release:
https://dev.bukkit.org/projects/serverlistmotd/files/3050444
https://github.com/strumswell/ServerlistMOTD-X/releases/tag/X-2020-09-05
