### ISSUE TITLE
%player% shows up <unknown>

### ISSUE THREAD

**Issue by Appmeurtre** [strumswell/ServerlistMOTD-X#8]
I'm using latest paper version and %player% shows up in game as <unknown>
I cleared up IP_UUID.dat thinking maybe its dedect me as Newbie (for check  if %% dont work) but it count me as Regular

**Comment by strumswell** [comment]
Hey! <unknown> normally appears for %player% in the regular (not newbie) motd if a player is registered in the IP_UUID.dat but not cached by Spigot in the usercache.json. This could happen when you create a fresh/ new Spigot server and copy an existing ServerlistMOTD folder with an existing IP_UUID.dat in it, as far as I know. Was this the case? Could you please check if your UUID/ username exists in the usercache.json?

Normally, this should fix itself when you join your server and Spigot registers you in the usercache.json. Can you test that for me?

**Comment by Appmeurtre** [comment]
> Hey! `<unknown>` normally appears for %player% in the regular (not newbie) motd if a player is registered in the IP_UUID.dat but not cached by Spigot in the usercache.json. This could happen when you create a fresh/ new Spigot server and copy an existing ServerlistMOTD folder with an existing IP_UUID.dat in it, as far as I know. Was this the case? Could you please check if your UUID/ username exists in the usercache.json?
> 
> Normally, this should fix itself when you join your server and Spigot registers you in the usercache.json. Can you test that for me?
> 
> Note: You should only edit the IP_UUID.dat when your server is stopped.

Thank you so much! It was due to usercache.json. Now everything is working

**Comment by strumswell** [comment]
Great to hear! Have a nice week. :)
