### ISSUE TITLE
Plugin breaks Load Order for other plugins/worlds

### ISSUE THREAD

**Issue by GenSecrets** [strumswell/ServerlistMOTD-X#9]
Just wanted to report a bug i found, if it can be fixed that's great but I noticed the home page said this would be no longer supported. Should it not be fixable, at least this is some info for passerby people. 

This happens when using Multiverse Core mainly, presumably will happen with other world loaders as well. It causes issues within other plugins and has no error messages that point to this plugin, I was just able to pin point it based on time of plugin being added and time of the issues in other plugins starting to arise

Inside of this plugin's config, there's the "world" feature. Whichever world is specified in this config will cause the server to force load that world first, **as soon as the server starts up**. Since it's force loading this, that causes Multiverse's world load to say "Woah what just happened? We can't load all worlds at once now, so we'll wait till after everything else (including plugins) is done and try again..." 

Normally, Multiverse would load the worlds (like wilderness, spawn, hub, etc) before most of the other plugins load(ones that set MV as a hard depend). Most common spigot/bukkit plugins that load are dependent on knowing information about the server worlds (like Towny, CMI, essentials, factions, etc) and if the worlds aren't loaded yet then that breaks features (such as Towny deleting all spawns for towns and outposts - [Issue 4048](https://github.com/TownyAdvanced/Towny/issues/4048), or CMI not loading random teleportation until a reload of the plugin). 

In order to fix this, there should be an option to change Multiverse or similar as a hard depend in this plugin's plugin.yml file? Not quite sure however I personally had to remove the plugin for the time being until I could test my theory to setting it as a hard depend so it loads after multiverse is finished

**Comment by strumswell** [comment]
Hey there. Thanks for reporting! I could add Multiverse-Core as a softdepend in the plugin.yml forcing ServerlistMOTD to load after it. Give me a minute and I'll provide you with a build to test.

**Comment by strumswell** [comment]
Here you go! I'm pretty busy atm so I couldn't test the build. Sorry for that. :( I hope this fixes it... 

[ServerlistMOTD_2020-06-03.jar.zip](https://github.com/strumswell/ServerlistMOTD-X/files/4722175/ServerlistMOTD_2020-06-03.jar.zip)

**Comment by strumswell** [comment]
Part of newest release:
https://dev.bukkit.org/projects/serverlistmotd/files/3050444
https://github.com/strumswell/ServerlistMOTD-X/releases/tag/X-2020-09-05
